### ISSUE TITLE
Build Duty Free Roadmap

### ISSUE THREAD

**Issue by ibagha** [concourse/dutyfree#130]
- [ ] Look into roadmapping tool
- [ ] Frameworks for roadmaps

Every roadmap item should reflect:
- [ ] What are we doing
- [ ] What impact will it have
- [ ] How are we tracking this impact

**Comment by pivotal-jamie-klassen** [comment]
FWIW GitHub Projects is a decent roadmap tool for the Concourse team, since we're working in the open and already using GitHub anyway - we have a ['project of projects'](https://github.com/concourse/concourse/projects/21). I'm sure @vito could comment on the PM experience. In particular he could certainly comment on shortcomings, having written project.concourse-ci.org (https://github.com/vito/cadet) at least partially to address the workflows that GitHub doesn't perfectly support out of the box.
